### ISSUE TITLE
Crash on python 3.5

### ISSUE THREAD

**Issue by rkhwaja** [google/google-api-python-client#139]
It crashes python itself during the build service call. I've tried it with YouTube and Drive

**Comment by nathanielmanistaatgoogle** [comment]
On what hardware, operating system, and specific version of Python 3.5? Do you have a stack trace that you can share with us? Or steps to reproduce?

**Comment by rkhwaja** [comment]
Windows 10. Python 3.5.0 (the released version). I'll get a stack trace, although I don't have PDBs for the python stuff.

I'm not sure which hardware details you're looking for, it's a physical windows PC, a few years old.

I can probably put together some simple sample code - it's almost copied directly from the examples.

**Comment by nathanielmanistaatgoogle** [comment]
Are you able to reproduce the problem on the same Windows platform with the same version of google-api-python-client but with Python 3.4 in place of Python 3.5?

**Comment by rkhwaja** [comment]
It doesn't happen with Python 3.4.3 on Windows 10, I use it all the time with the latest versions of oauthclient and google-api-python-client. It also doesn't happen with Python 3.5 on Windows 7. I'm not sure about Python 3.5 and Windows 8.

**Comment by nathanielmanistaatgoogle** [comment]
My strong suspicion is that google-api-python-client isn't doing anything fancy or weird, and that if you're able to create a reproduction case for the defect then the reproduction case will be able to be reduced in such a way that the google-api-python-client involvement shakes out.

But suspicion isn't the same thing as a finding of truth...

**Comment by leVirve** [comment]
Maybe it's the problem of previous Windows 10 build.
I have the same problem before, but now with newest build 10586, I can use python-client normally as it should.
(I'm on Windows 10 build 10586 64bit, Python 3.5 64bit)

**Comment by rkhwaja** [comment]
I updated to Windows 10 build 10586 64bit, Python 3.5 64bit and it still crashes. I tracked it down a bit more and I find that it's crashing in the following call in oauth2client\locked_file.py in the open_and_lock function:

hfile = win32file._get_osfhandle(self._fh.fileno())

**Comment by sbneto** [comment]
I am having the same problem, but only when debugging with pydev (the built-in version in PyCharm). I am working with Anaconda running python 3.5.

```
C:\Anaconda3\python.exe "C:\Program Files (x86)\JetBrains\PyCharm 5.0\helpers\pydev\pydevd.py" --multiproc --client 127.0.0.1 --port 51935 --file C:/sam/phd/repo/test.py
C:\Anaconda3\lib\site-packages\IPython\utils\traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
pydev debugger: process 5584 is connecting

Connected to pydev debugger (build 143.595)

Process finished with exit code 255
```

The problem happens when I try to build the resource object

```
def get_service():
    """returns an initialized and authorized bigquery client"""
    credentials = GoogleCredentials.get_application_default()
    if credentials.create_scoped_required():
        credentials = credentials.create_scoped(
            'https://www.googleapis.com/auth/bigquery')
    return build('bigquery', 'v2', credentials=credentials) ### Crashes Here ###
```

After the program suddenly finishes, I get a Windows Error Event.

```
Faulting application name: python.exe, version: 3.5.150.1013, time stamp: 0x563e4ddb
Faulting module name: MSVCR100.dll, version: 10.0.40219.325, time stamp: 0x4df2bcac
Exception code: 0xc0000417
Fault offset: 0x0000000000070468
Faulting process id: 0x1790
Faulting application start time: 0x01d123fbf6508975
Faulting application path: C:\Anaconda3\python.exe
Faulting module path: C:\WINDOWS\SYSTEM32\MSVCR100.dll
Report Id: 664a7090-d5c8-4167-834c-127af5857f8c
Faulting package full name: 
Faulting package-relative application ID: 
```

I also tracked the problem to the same place as @rkhwaja pointed out. I suspect that the problem is that Python 3.5 for Windows is now compiled with Visual Studio 2015 (https://docs.python.org/3/using/windows.html#compiling-python-on-windows) instead of Visual Studio 2008 and 2010 (http://stackoverflow.com/questions/29909330/microsoft-visual-c-compiler-for-python-3-4). This might have introduced an cpp call incompatibility with the sdk compiled by Google (https://cloud.google.com/sdk/) that is used to build the object, but that is just a guess. The strangest thing however is that I do not have any problems when I am not debugging the code.

Another possibility is that the MSVCR100.dll that I have is incompatible with Google's compilation. Since this dll is shipped with Python 3.4, all installations have access to the same binary. This, however, does not seem to be the case anymore for Python 3.5. Users have to install the dll independently from Python and might have access to different compilations that might be conflicting (https://bugs.python.org/issue24872#msg248654).

**Comment by rkhwaja** [comment]
Update - still crashes on python 3.5.1 64-bit on windows 10

**Comment by rkhwaja** [comment]
This is logged on the oauth2client project now at https://github.com/google/oauth2client/issues/361.

There's also a workaround detailed there.
