### ISSUE TITLE
Large memory footprint

### ISSUE THREAD

**Issue by dabaitu** [google/google-api-python-client#198]
I've recently noticed my download script which uses chunked downloading of 250MB would use nearly 2GB of ram when downloading a file of size ~7GB. The string buffer gets cleaned for every 250MB chunk, so I don't expect that large of a ram usage.

Please let me know what other information is needed here.

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free explain why you believe fixing it is essential for users of this client library.

**Comment by zachliu** [comment]
@mattwhisenhunt What's the work-around? I'm using v1.7.4 and still experiencing the same issue.

**Comment by busunkim96** [comment]
@zachliu Please open another issue referencing this one with a minimal reproduction of the problem you are experiencing. It's best for you to open a new issue as it's easy for comments on already closed issues to be lost. 

Thanks.

**Comment by zachliu** [comment]
@busunkim96 Will do :+1:. It's just that Mr. Whisenhunt left a huge cliffhanger in his post: there's a workaround, but i'm not gonna say it :joy:
