### ISSUE TITLE
Request for Storage Resumable Upload Endpoint Retrieval

### ISSUE THREAD

**Issue by devonbalicki** [google/google-api-python-client#240]
In the JSON API, the response to requests for resumable uploads contains a URI that can then be used to start the upload session. (https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload#save-session-uri) 

> Example: Saving the resumable session URI
> 
> The following example shows a response that includes a resumable session URI:
> 
> ```
> HTTP/1.1 200 OK
> Location: https://www.googleapis.com/upload/storage/v1/b/myBucket/o?uploadType=resumable&upload_id=xa298sd_sdlkj2
> Content-Length: 0
> ```

The analogous method for this in the Python client behaves slightly differently in that it takes the actual file data and executes the upload in one request. (https://developers.google.com/api-client-library/python/guide/media_upload#resumable-media-chunked-upload) 

```
media = MediaFileUpload('pig.png', mimetype='image/png', resumable=True)
request = farm.animals().insert(media_body=media, body={'name': 'Pig'})
response = None
while response is None:
  status, response = request.next_chunk()
  if status:
    print "Uploaded %d%%." % int(status.progress() * 100)
print "Upload Complete!"

```

**It would be very helpful if there were a method in the Python client that worked more similarly to the original JSON API spec, in that it just returned a URI that could be used later for starting the upload session.** In my particular use case, the system that is sending these requests is separate from the system that is actually  executing the upload. If there's something I'm missing about how to use the Python API to achieve this, please let me know.

I realize that I could achieve it by just using the JSON API using urlfetch, but I would ideally like to be batching these using the Python client (https://developers.google.com/api-client-library/python/guide/batch) as doing so with the regular JSON API requires constructing   "mixed/multipart" HTTP requests which I think will require some special library, and the Python client makes this a much cleaner process.

**Comment by jonparrott** [comment]
I'm happy to review any pull requests to add this functionality in a safe manner, but at the moment we are not adding additional features to the library.

**Comment by ThatsAMorais** [comment]
I am confronting the same issue which I parameterize as follows:
 * Client must be the initiator and uploader, because we need the file to be placed in a bucket near or in that client's region for the lowest-latency user experience possible.
 * Client must be the initiator, because it has the file.
 * Server must generate the signatures required as part of the URLs, along with the URL containing the bucket and destination object itself
 * Server does not receive the file, so it cannot be uploaded there.
 * The upload must be resumable due to expected file size ranges

I can construct a POST on the server-side using a bearer token as authorization, but that initiates it in the server's region, not the client's. I can easily craft a simpler PUT signed URL but that does not support resumable. 

That leaves me having to follow the directions in [POST Object](https://cloud.google.com/storage/docs/xml-api/post-object) as directed by the [Signed URL docs regarding Signed Resumable Uploads](https://cloud.google.com/storage/docs/access-control/signed-urls#signing-resumable). 

This flow seems more complicated for clients, and composing the multipart form request on the server for the client entails constructing and returning: 
 * the upload url
 * signature
 * policy document
 * headers that went into the signature that the client must use in their request

Now they have what they need, but it requires much documentation to explain that they must:
1. Construct the multipart form POST
2. POST to GCS with no data
3. Read the Location header from the POST response
4. PUT file data to this session URL in chunks

If I can actually do as suggested in the Signed URL documentation then I will gladly implement it in the SDK and post a PR.

I might have preferred the feature be implemented to overload PUTting to a signed url via the `x-goog-resumable: start` header, along with no data, which would produce a session URI like the POST.

**Comment by ThatsAMorais** [comment]
I believe my problem may be unique and i should have made another issue for it. 

I made a mistake in my previous post. I was linked to this documentation on Resumable Uploads from the signed url documentation: https://cloud.google.com/storage/docs/xml-api/resumable-upload. However, that flow is not signature-based, it uses a Bearer token; the POST Object docs depict an approach that is signature-based.

Specifically, the advice in the signed url docs is as follows, regarding avoiding initiating in the server's region:
> Resumable uploads are pinned in the region they start in. For example, if you create a resumable upload URL in the US and give it to a client in Asia, the upload still goes through the US. Performing a resumable upload in a region where it wasn't initiated can cause slow uploads. To avoid this, you can have the initial POST request constructed and signed by the server, but then give the signed URL to the client so that the upload is initiated from their location. Once initiated, the client can use the resulting session URI normally to make PUT requests that do not need to be signed.

The documentation also warns that session URLs should not be traded as they provide authenticated access to upload anything to the bucket.

Can I construct and sign the URL like a PUT and have the client send the upload as a POST?

**Comment by jonparrott** [comment]
I believe "create_signed_url" or "create_policy_document" is what you're
looking for.

(Sorry for terseness, I'm traveling. Hopefully one of the other maintainers
can help as well)

**Comment by ThatsAMorais** [comment]
Thanks for pointing me to `Bucket.generate_upload_policy`! Should be helpful for what I'm doing.

Is it advised to trust clients with sending this signed POST, getting session-id URIs to which to post, etc? The conditions in the policy document generated by the server should be able to limit what that client can do/upload with that right?

**Comment by jonparrott** [comment]
Exactly

**Comment by ThatsAMorais** [comment]
To make this POST+policy request initiate a resumable upload, can I include `x-goog-resumable: start` in the form fields? Is it implicitly resumable?

Its interesting because there's a separate doc for resumable that uses the Bearer token flow, initiated by a POST with follow-up PUT session URIs. However, constructing this POST enables me to have the client initiate the upload, but its not clear whether this flow is resumable.

I go in circles between these 3 documents: 
 * https://cloud.google.com/storage/docs/access-control/signed-urls
 * https://cloud.google.com/storage/docs/xml-api/resumable-upload
 * https://cloud.google.com/storage/docs/xml-api/post-object

**Comment by jonparrott** [comment]
I'm don't think you can do resumable with the policy document / post method. From the docs, it seems that you can set `x-goog-meta-*` stuff in the POST request but not `x-goog-resumable`. However, I could be wrong.

I think if you want to do resumable, you'll need to have the server start the resumable upload using create_signed_url.

I'm going to close this issue as the original feature request is available in google-cloud-storage.

**Comment by ThatsAMorais** [comment]
If the server starts the resumable upload then the client will be uploading across regions in the case where the API server is in a different region from the client making the upload request.

**Comment by ThatsAMorais** [comment]
It is clear to me now that gsutil supports a `-m` value of `RESUMABLE`, which generates a signed URL that is resumable. The documentation for this is incredibly misleading.

Basically, just as you would generate a Signed URL to be PUT, you change the method (in the signature) to be POST, and include the x-goog-resumable header in the signature and on the request.

**Comment by ThatsAMorais** [comment]
I am going to update your docs if possible with the POST flow, and send a PR. The `generate_signed_url` method in the SDK should support POST as a method such that it adds the resumable header, and I can create a PR for that, too.

**Comment by jonparrott** [comment]
That sounds awesome, thanks @ThatsAMorais!

**Comment by ThatsAMorais** [comment]
No problem at all! https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4789

Can you point me to this documentation if its open source? I'll add some for this if I can.
