### ISSUE TITLE
v1.6.1 HttpError 403 "Insufficient Permission"

### ISSUE THREAD

**Issue by jmgirven** [google/google-api-python-client#346]
I happened to try updating google-api-python-client from 1.5.5 to 1.6.1. It causes my YouTube Data API v3 code to always fail with a HttpError. An example to reproduce is:

    from apiclient.discovery import build
    DEVELOPER_KEY = "<Insert key>"
    youtube = build("youtube", "v3", developerKey=DEVELOPER_KEY)
    youtube.videos().list(id="xGG56MWgbOA", part="id").execute()

This returns a successful response on 1.5.5, but raises a HttpError on 1.6.1:

    HttpError: <HttpError 403 when requesting https://www.googleapis.com/youtube/v3/videos?alt=json&part=id&id=xGG56MWgbOA&key=<Insert key> returned "Insufficient Permission">

Visiting the specified link in a browser returns a valid response. Is there some usage change I am not aware of?

**Comment by jonparrott** [comment]
@jmgirven interesting. If you pass in `http=httplib2.Http()` to `build` does that fix the issue?

**Comment by jmgirven** [comment]
It does, yep.

**Comment by jonparrott** [comment]
Alright. I know what's going on.

We added support for application default credentials in 1.6.0. What's happening is that you're getting default OAuth credentials attached to your requests, but you shouldn't be because you specified an API key. I'll try to get a fix out soon, in the meantime specifying your own http should short-circuit the application default credentials logic.
