### ISSUE TITLE
Update google-api-python-client in light of OAuth2Client Deprecation

### ISSUE THREAD

**Issue by weitaiting** [google/google-api-python-client#415]
Google's OAuth2Client library was recently deprecated in favour of google-auth and oauthlib. (See the [README.md](https://github.com/google/oauth2client) at google/oauth2client)

However, OAuth2Client is still used in google-api-python-client.
([See here](https://github.com/google/google-api-python-client/search?utf8=%E2%9C%93&q=oauth2client&type=))

Will it be necessary to update all instances where OAuth2Client is used in google-api-python-client to use google-auth and oauthlib instead?

**Comment by jonparrott** [comment]
oauth2client is deprecated, but not gone. Its frozen, but will still receive bug fixes for critical issues. This library supports both oauth2client and the newer library, so there's no action needed here.

**Comment by amureki** [comment]
@jonparrott 
>This library supports both...
I assume, then it should not require both of them, but at least one. Because now it always requires oauth2lib

So, for example, we moved to google-auth lib everywhere we could, but since we are using [google-api-python-client](https://github.com/google/google-api-python-client) we still have to have oauth2client dependency and maintain it, because of this imports here:
https://github.com/google/google-api-python-client/blob/master/googleapiclient/discovery.py#L75

Is it going to support both libs properly, meaning I can use either google-auth or oauth2client separately, but not together?


Thank you for maintaining this and helping us, this is really important.

**Comment by jonparrott** [comment]
> Is it going to support both libs properly, meaning I can use either google-auth or oauth2client separately, but not together?

Right. Well, you can actually use them together (you can use oauth2client for one call to `build` and google-auth for some other call to `build`).

> because of this imports here:

I'd be happy to accepts PRs that reduce non-auth dependencies on oauth2client so that it could possibly be made an optional dependency.

**Comment by amureki** [comment]
@jonparrott got it, thank you for nice answer!

That's a good opportunity for OSS contributors to make it real. 
I will try to have a look at my free time into it, maybe I could help! :)
