### ISSUE TITLE
Dependency question: why google_auth_httplib2 is required for HAS_GOOGLE_AUTH = true?

### ISSUE THREAD

**Issue by bobintornado** [google/google-api-python-client#419]
Why `google_auth_httplib2` is required to flap `HAS_GOOGLE_AUTH = True`?

`google-auth-library-python` and `google-auth-library-python-httplib2` are two different repos. 

I am trying to use google auth, but it took me a while to realize that I need to include these both pacakges.

**Comment by jonparrott** [comment]
The package description for [`google-auth-httplib2`](https://pypi.python.org/pypi/google-auth-httplib2) sums it up as:

> httplib has lots of problems such as lack of threadsafety and and insecure usage of TLS. Using it is highly discouraged. This library is intended to help existing users of oauth2client migrate to google-auth.

The httplib2 transport was not included in the core `google-auth` library specifically because we do not want to support its long term usage. This library is the exception - the is inextricably tied to httplib2 and we are supporting this library long term. What this means in practical terms is that unless an issue in `google-auth-httplib2` affects this library, it will be considered low priority.

**Comment by bobintornado** [comment]
@jonparrott 

I see. So the reason for httplib2 not included in `google-auth` is `we do not want to support its long term usage`.

So it long term the plan is to flip `HAS_GOOGLE_AUTH = True` without `google_auth_httplib2`?

**Comment by jonparrott** [comment]
No, because we do not plan to replace httplib2 in this library as doing so
would cause too many breaking changes for our users.

**Comment by bobintornado** [comment]
Got it.

Appreciate the information.
