### ISSUE TITLE
ImportError: No module named google.cloud

### ISSUE THREAD

**Issue by RjLi13** [google/google-api-python-client#426]
Apologies if this question has been answered, but I installed the google-api-python-client using pip install. When I do a pip list, I see the google-api-python-client listed in packages installed, yet when I open the python terminal, it complains google / google.cloud are not modules that exist. I tried uninstall and reinstall but I get the same error. What's happening? If it matters I'm under a company proxy, though I manage to install python libraries through pip with proxy, using python 2.7.13, and I have OS X 10.12.6

**Comment by jonparrott** [comment]
@RjLi13 this is the library for `googleapiclient`. If you're looking for the libraries that provide `google.cloud`, see [here](https://github.com/googlecloudplatform/google-cloud-python). 

This is confusing because we actually have two sets of client libraries. You can read more about that here: https://cloud.google.com/apis/docs/client-libraries-explained
