### ISSUE TITLE
library is using a deprecated batch endpoint

### ISSUE THREAD

**Issue by jay0lee** [google/google-api-python-client#487]
The libary currently has www.googleapis.com/batch hardcoded as the endpoint for batch API requests unless caller manually sets batch_uri. See:

https://github.com/google/google-api-python-client/blob/master/googleapiclient/http.py#L1089

per [Google Developers blog post](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html) this universal endpoint is being turned down in favor of per-API endpoints.

library needs to:
1. ensure all members of the batch are homogenous (same API) and throw an error if they're not.
2. utilize the batchPath from the individual API rather than the generic one, this would be something like:

service._rootDesc['rootUrl'] + service._rootDesc['batchPath']

**Comment by jonparrott** [comment]
Turns out this library is doing the right thing, but only if you construct the `BatchHTTPRequest` using `service.new_batch_http_request`. This method is documented in the docs [here](https://developers.google.com/api-client-library/python/guide/batch).

I've sent a PR to add a helpful warning if you construct `BatchHTTPRequest` manually and specify the legacy URI. This is the best compromise I can see that doesn't break the library's interface.

**Comment by jay0lee** [comment]
The docs also need updating, they're still importing the old camel case call:

https://developers.google.com/api-client-library/python/guide/batch

**Comment by jonparrott** [comment]
Yeah but it's not using it. Easy to fix.
