### ISSUE TITLE
Switch from "uritemplate" to "uritemplate.py"

### ISSUE THREAD

**Issue by sloria** [google/google-api-python-client#57]
There are at least 2 URI template packages on the PyPI: [uritemplate](https://pypi.python.org/pypi/uritemplate/0.6) and [uritemplate.py](https://pypi.python.org/pypi/uritemplate.py/0.3.0). Both of these packages use `uritemplate` as the package name to be imported, which causes a conflict when both are installed (see https://github.com/sigmavirus24/uritemplate/issues/14).

I propose that this project depend on  `uritemplate.py` because:

- `uritemplate.py` is API-compatible with `uritemplate`, but the reverse is not true. I have confirmed that this library works with uritemplate.py.
- Other projects depend on `uritemplate.py`. For example, we are currently working on a project that depends on both `github3.py` (GitHub API client) and `google-api-python-client`. Installing both results in an immediate `ImportError` due to the `uritemplate` conflict.

This  is a simple, low-risk change that would aid compatibility with other projects.

Thoughts?

**Comment by pedgar** [comment]
+1     We are having the same issue of incompatibility between the 'github3.py' and 'google-api-python-client' libraries.

**Comment by nathanielmanistaatgoogle** [comment]
Even though the technical aspect of the change sounds very simple I'd like to know more before welcoming a pull request welcoming the change. This smells like a political problem, like an unclean fork. What's being done upstream between uritemplate and uritemplate.py to resolve the problem?

**Comment by rodneykeeling** [comment]
Any update on this issue? Discogs is trying to use this client for the YouTube v3 API but we are running into this same error.

**Comment by gcarothers** [comment]
This hasn't gone away. As to the upstream, it seems that uritemplate.py claims API compatibility with  uritemplate which hasn't had an update since Aug 27, 2013. While it may be a political issue the effect is very real, running an ansible playbook that needs to talk to google cloud and github at the same time is... challenging

**Comment by nathanielmanistaatgoogle** [comment]
For folks subscribed to this issue but not otherwise watching the project: #146 just went by and I didn't realize during its review that this issue was opened on the matter. Has this issue budged at all in the last few months? I see recent commits over at https://github.com/uri-templates/uritemplate-py/commits/master including one by @graingert.

**Comment by nathanielmanistaatgoogle** [comment]
For everyone affected by this issue: has anyone ever bothered to contact the maintainers of both libraries and simply ask what's up? It's been nearly three years since either of them cut a release; I wonder if they can be merged and the whole problem solved properly.
